title = "tantum quantum"
baseURL = "//tantumquantum.site"
languageCode = "en-us"
theme = "ananke"
resourceDir = "/resources"
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "tantum quantum"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "tantumquantum"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Physics, climate change, politics, maybe more"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/gabrielwoolls"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/ungovernable.jpg"
  recent_posts_number = 2